### ISSUE TITLE
darwin release --setup error: bad argument #1 to 'stat'

### ISSUE THREAD

**Issue by kevinw** [johnae/spook#13]
Downloaded the latest Darwin release, and tried `spook --setup`, and got this:

```
 🐇  spook --setup
Error: [string "vendor"]:0: bad argument #1 to 'stat' (cannot convert 'bool' to 'const char *')
```

**Comment by johnae** [comment]
Ahh. Probably because I mostly use Linux. Will look into that.

**Comment by johnae** [comment]
@kevinw Release 0.5.2 with a fix should be up soon.

**Comment by johnae** [comment]
Btw. This shouldn't have been a problem just on Darwin. Looking at the compiled Lua it was just plain wrong - still it worked as intended on Linux for unknown reasons.
