### ISSUE TITLE
New configuration DSL

### ISSUE THREAD

**Issue by johnae** [johnae/spook#4]
Currently there's a branch new-configuration with a simple DSL in it. Looks like this:

```moonscript
log_level "INFO"
spooked false

watch {"lib", "spec"}

map {
  {"^(spec)/(spec_helper%.moon)": (a,b) -> "spec"}
  {"^spec/(.*)%.moon": (a,b) -> "spec/#{a}.moon"}
  {"^lib/(.*)%.moon": (a,b) -> "spec/#{a}_spec.moon"}
}

notifier "path/to/notifier.moon"
-- or
notifier {
   start: (changed_file, mapped_file) -> do_stuff
   finish: (status, changed_file, mapped_file) -> do_stuff
}

command "./spook -f spec/support/run_busted.lua"
```

While that surely works, perhaps it might be useful to go a bit further (before merging)?

A more advanced option might be:

```moonscript
log_level "INFO"
spooked false

watch "lib spec" ->
   command "./spook -f spec/support/run_busted.lua"
   map "^(spec)/(spec_helper%.moon)": (a,b) -> "spec"
   map "^spec/(.*)%.moon": (a,b) -> "spec/#{a}.moon"
   map "^lib/(.*)%.moon": (a,b) -> "spec/#{a}_spec.moon"

watch "playground" ->
   command "./spook -f"
   map "^playground/(.*)%.moon": (a) -> "playground/#{a}.moon"

notifier "path/to/notifier.moon"
-- or
notifier {
   start: (changed_file, mapped_file) -> do_stuff
   finish: (status, changed_file, mapped_file) -> do_stuff
}
-- or maybe
notifier ->
   start (changed_file, mapped_file) -> do_stuff
   finish (status, changed_file, mapped_file) -> do_stuff

command "./spook -f spec/support/run_busted.lua"
```

Might also want to think some more on sane defaults... should there be a default command? Is it meaningful to provide different notifiers per watch statement?

Could some be implemented while keeping watches simple for now while later they could support custom notifiers (without having to - again - change the Spookfile format and force anyone using this to change theirs, i.e backward compatible). Not that anyone but me is using spook afaik :-).

**Comment by johnae** [comment]
If this was implemented the internals would probably change a bit. Today it's kind of:

main runs spook (a function), spook sets up watches and executes commands on changes. 

Perhaps it would need to change to:

main runs spook (a function), spook sets up watches - more than one "instance" - they execute commands on changes.

So an internal structure more similar to the configuration in a sense.

**Comment by johnae** [comment]
Should probably change "spooked" into something easily understandable.

**Comment by johnae** [comment]
Fleshing this out it's going to look something like:

```moonscript
log_level "INFO"
show_command false

watch "lib", "spec", ->
   command "./spook -f spec/support/run_busted.lua"
   map "^(spec)/(spec_helper%.moon)", (a,b) -> "spec"
   map "^spec/(.*)%.moon", (a) -> "spec/#{a}.moon"
   map "^lib/(.*)%.moon", (a) -> "spec/#{a}_spec.moon"

watch "playground" ->
   command "./spook -f"
   map "^playground/(.*)%.moon", (a) -> "playground/#{a}.moon"
```

**Comment by johnae** [comment]
https://github.com/johnae/spook/pull/5

**Comment by nilnor** [comment]
Just a thought - instead of using the guard inspired `map`, things could be made more explicit as well as more generic. Instead of always executing the command it could be that the handler could do whatever, and run external commands only if desired (the example below also uses `on_changed` instead of `map`:

```moonscript
watch "lib spec" ->
   cmd = command "./spook -f spec/support/run_busted.lua"
   on_changed "^(spec)/(spec_helper%.moon)": (a,b) -> cmd "spec"
```

The `command` helper above could be used to construct a callable object that adheres to Spook's internal demands with regards to reporting, etc. This could then be used to run other snippets in reaction to file changes, perhaps Spook plugins in Lua/Moonscript such as custom linters or whatnot.

**Comment by johnae** [comment]
Yeah that's interesting enough :-). I've been thinking along those lines myself... for spook to not be JUST a test runner. It could be alot more and easily I think.

**Comment by johnae** [comment]
@nilnor So you were thinking of enabling something like this:

```moonscript
echo = (s) ->
   print s

watch "lib", "spec", ->
   cmd = command "./spook -f spec/support/run_busted.lua"
   on_changed "^(spec)/(spec_helper%.moon)", -> cmd "spec"
   on_changed "^(spec)/(spec_helper%.moon)", (a,b) -> echo "HEY! #{a}/#{b}"
```

**Comment by nilnor** [comment]
@johnae Yup!

**Comment by johnae** [comment]
Done as of https://github.com/johnae/spook/pull/5
